# Generated by Django 5.1.6 on 2025-03-03 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicationid', models.AutoField(primary_key=True, serialize=False)),
                ('applicationdate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetid', models.AutoField(primary_key=True, serialize=False)),
                ('assettype', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True, null=True)),
                ('installationdate', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('lastmaintenancedate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Censusevent',
            fields=[
                ('censuseventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventtype', models.CharField(max_length=100)),
                ('eventdate', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'censusevent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizenid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('contactnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('educationlevel', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'citizen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cultivationrecord',
            fields=[
                ('cultivationid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('croptype', models.CharField(blank=True, max_length=100, null=True)),
                ('cultivatedarea', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yield_field', models.DecimalField(blank=True, db_column='yield', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'cultivationrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('householdid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('annualincome', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('totalmembers', models.IntegerField(blank=True, null=True)),
                ('propertyvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'household',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('landid', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'land',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginPanchayat',
            fields=[
                ('panchayatid', models.AutoField(primary_key=True, serialize=False)),
                ('panchayatname', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'login_panchayat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('panchayatid', models.AutoField(primary_key=True, serialize=False)),
                ('panchayatname', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'panchayat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicerequest',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requesttype', models.CharField(max_length=100)),
                ('requestdate', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'servicerequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccinationrecord',
            fields=[
                ('vaccinationid', models.AutoField(primary_key=True, serialize=False)),
                ('vaccinename', models.CharField(max_length=100)),
                ('dateadministered', models.DateField()),
            ],
            options={
                'db_table': 'vaccinationrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfareprogram',
            fields=[
                ('programid', models.AutoField(primary_key=True, serialize=False)),
                ('programname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('eligibilitycriteria', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('startdate', models.DateField()),
                ('managingdepartment', models.CharField(blank=True, max_length=255, null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'welfareprogram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Censusparticipation',
            fields=[
                ('censuseventid', models.OneToOneField(db_column='censuseventid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.censusevent')),
            ],
            options={
                'db_table': 'censusparticipation',
                'managed': False,
            },
        ),
    ]
