# Generated by Django 5.1.6 on 2025-03-03 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('citizenid', models.ForeignKey(db_column='citizenid', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='login.citizen')),
            ],
        ),
    ]
